//
// This file is automatically generated - do not edit.
//

#include <pico/platform.h>

#define BLOCK_SIZE 1024
#define NUM_BLOCKS 64

extern const uint8_t *disk_blocks[NUM_BLOCKS];

// One of these blocks will contain the file contents
extern uint8_t file_contents[BLOCK_SIZE];

// Load the key file starting at offset FILE_CONTENTS_BLOCK_OFFSET. The
// initial portion of the file will be generated.
// #define FILE_CONTENTS_BLOCK_OFFSET (4+FILE_PREFIX_LEN)

